'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Ingles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Presentation.Ingles", GetType(Ingles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PHYSICIANS AGENDA.
        '''</summary>
        Friend Shared ReadOnly Property Agenda_titulo() As String
            Get
                Return ResourceManager.GetString("Agenda_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICAL SELF-CONSULTATION SYSTEM.
        '''</summary>
        Friend Shared ReadOnly Property app_titulo() As String
            Get
                Return ResourceManager.GetString("app_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En este menu podras ver y buscar los horarios
        '''y lugares de trabajo de los medicos, para asi poder pedir hora en la recepcion.
        '''Pudiendo filtrar por especialidad o buscar un medico por su primer nombre..
        '''</summary>
        Friend Shared ReadOnly Property ayuda_agenda() As String
            Get
                Return ResourceManager.GetString("ayuda_agenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Para realizar una consulta
        '''1. Seleccione sus sintomas
        '''2. Aprete el boton CONSULTAR
        '''3. Si lo desea aprete el boton chat para iniciar un chat con un medico.
        '''</summary>
        Friend Shared ReadOnly Property ayuda_consulta() As String
            Get
                Return ResourceManager.GetString("ayuda_consulta", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En este menu podras ver tus historial de consultas y que medico te atendio, pudiendo filtrar por fecha
        '''La segunda fecha debe ser mayo a la primera.
        '''</summary>
        Friend Shared ReadOnly Property ayuda_historial() As String
            Get
                Return ResourceManager.GetString("ayuda_historial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a WELCOME.
        '''</summary>
        Friend Shared ReadOnly Property Bienvenido() As String
            Get
                Return ResourceManager.GetString("Bienvenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a TO ACCEPT.
        '''</summary>
        Friend Shared ReadOnly Property btn_aceptar() As String
            Get
                Return ResourceManager.GetString("btn_aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICAL AGENDA.
        '''</summary>
        Friend Shared ReadOnly Property btn_Agenda() As String
            Get
                Return ResourceManager.GetString("btn_Agenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a APPLICATION.
        '''</summary>
        Friend Shared ReadOnly Property btn_app() As String
            Get
                Return ResourceManager.GetString("btn_app", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HELP.
        '''</summary>
        Friend Shared ReadOnly Property btn_ayuda() As String
            Get
                Return ResourceManager.GetString("btn_ayuda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEARCH.
        '''</summary>
        Friend Shared ReadOnly Property btn_Buscar() As String
            Get
                Return ResourceManager.GetString("btn_Buscar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CHANGE.
        '''</summary>
        Friend Shared ReadOnly Property btn_cambiar() As String
            Get
                Return ResourceManager.GetString("btn_cambiar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CANCEL.
        '''</summary>
        Friend Shared ReadOnly Property btn_cancelar() As String
            Get
                Return ResourceManager.GetString("btn_cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CLOSE.
        '''</summary>
        Friend Shared ReadOnly Property btn_cerrar() As String
            Get
                Return ResourceManager.GetString("btn_cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a LOG OUT.
        '''</summary>
        Friend Shared ReadOnly Property btn_cerrarSesion() As String
            Get
                Return ResourceManager.GetString("btn_cerrarSesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CHAT.
        '''</summary>
        Friend Shared ReadOnly Property btn_chat() As String
            Get
                Return ResourceManager.GetString("btn_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CHATS.
        '''</summary>
        Friend Shared ReadOnly Property btn_chats() As String
            Get
                Return ResourceManager.GetString("btn_chats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONSULT.
        '''</summary>
        Friend Shared ReadOnly Property btn_consultar() As String
            Get
                Return ResourceManager.GetString("btn_consultar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE.
        '''</summary>
        Friend Shared ReadOnly Property btn_crear() As String
            Get
                Return ResourceManager.GetString("btn_crear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a DASHBOARD.
        '''</summary>
        Friend Shared ReadOnly Property btn_dashBoard() As String
            Get
                Return ResourceManager.GetString("btn_dashBoard", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REMOVE.
        '''</summary>
        Friend Shared ReadOnly Property btn_eliminar() As String
            Get
                Return ResourceManager.GetString("btn_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BETWEEN.
        '''</summary>
        Friend Shared ReadOnly Property btn_Entre() As String
            Get
                Return ResourceManager.GetString("btn_Entre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SEND.
        '''</summary>
        Friend Shared ReadOnly Property btn_enviar() As String
            Get
                Return ResourceManager.GetString("btn_enviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICAL RECORD.
        '''</summary>
        Friend Shared ReadOnly Property btn_fichaMed() As String
            Get
                Return ResourceManager.GetString("btn_fichaMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FILTER.
        '''</summary>
        Friend Shared ReadOnly Property btn_Filtrar() As String
            Get
                Return ResourceManager.GetString("btn_Filtrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SAVE.
        '''</summary>
        Friend Shared ReadOnly Property btn_guardar() As String
            Get
                Return ResourceManager.GetString("btn_guardar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECORD.
        '''</summary>
        Friend Shared ReadOnly Property btn_historial() As String
            Get
                Return ResourceManager.GetString("btn_historial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT.
        '''</summary>
        Friend Shared ReadOnly Property btn_ingresar() As String
            Get
                Return ResourceManager.GetString("btn_ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INSERT.
        '''</summary>
        Friend Shared ReadOnly Property btn_ingresar2() As String
            Get
                Return ResourceManager.GetString("btn_ingresar2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICS.
        '''</summary>
        Friend Shared ReadOnly Property btn_ingrMed() As String
            Get
                Return ResourceManager.GetString("btn_ingrMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a START.
        '''</summary>
        Friend Shared ReadOnly Property btn_Iniciar() As String
            Get
                Return ResourceManager.GetString("btn_Iniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFY.
        '''</summary>
        Friend Shared ReadOnly Property btn_modificar() As String
            Get
                Return ResourceManager.GetString("btn_modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PATHOLOGIES.
        '''</summary>
        Friend Shared ReadOnly Property btn_patologia() As String
            Get
                Return ResourceManager.GetString("btn_patologia", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECOVER.
        '''</summary>
        Friend Shared ReadOnly Property btn_recuperar() As String
            Get
                Return ResourceManager.GetString("btn_recuperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RESTORE.
        '''</summary>
        Friend Shared ReadOnly Property btn_restablecer() As String
            Get
                Return ResourceManager.GetString("btn_restablecer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a GET OUT.
        '''</summary>
        Friend Shared ReadOnly Property btn_salir() As String
            Get
                Return ResourceManager.GetString("btn_salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REQUESTS.
        '''</summary>
        Friend Shared ReadOnly Property btn_soliChat() As String
            Get
                Return ResourceManager.GetString("btn_soliChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USER.
        '''</summary>
        Friend Shared ReadOnly Property btn_usuario() As String
            Get
                Return ResourceManager.GetString("btn_usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT YOUR SYMPTOMS.
        '''</summary>
        Friend Shared ReadOnly Property consu_titulo() As String
            Get
                Return ResourceManager.GetString("consu_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sunday.
        '''</summary>
        Friend Shared ReadOnly Property Dom() As String
            Get
                Return ResourceManager.GetString("Dom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Double click on a cell to select the item.
        '''</summary>
        Friend Shared ReadOnly Property elimiAclara() As String
            Get
                Return ResourceManager.GetString("elimiAclara", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Pathologies.
        '''</summary>
        Friend Shared ReadOnly Property enfermedad() As String
            Get
                Return ResourceManager.GetString("enfermedad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Please wait.
        '''</summary>
        Friend Shared ReadOnly Property EsperaChat() As String
            Get
                Return ResourceManager.GetString("EsperaChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Filter.
        '''</summary>
        Friend Shared ReadOnly Property filtro() As String
            Get
                Return ResourceManager.GetString("filtro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RELATED SYMPTOMS.
        '''</summary>
        Friend Shared ReadOnly Property groupBoxSintomas() As String
            Get
                Return ResourceManager.GetString("groupBoxSintomas", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a This date must be older.
        '''</summary>
        Friend Shared ReadOnly Property Histo_aclara() As String
            Get
                Return ResourceManager.GetString("Histo_aclara", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HISTORY OF CONSULTATIONS.
        '''</summary>
        Friend Shared ReadOnly Property Histo_titulo() As String
            Get
                Return ResourceManager.GetString("Histo_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Example: 09:00 to 19:30.
        '''</summary>
        Friend Shared ReadOnly Property horaEjemplo() As String
            Get
                Return ResourceManager.GetString("horaEjemplo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Element identifier.
        '''</summary>
        Friend Shared ReadOnly Property idElemento() As String
            Get
                Return ResourceManager.GetString("idElemento", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ENTER SYMPTOMS / PATHOLOGIES.
        '''</summary>
        Friend Shared ReadOnly Property ingGerente() As String
            Get
                Return ResourceManager.GetString("ingGerente", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ENTER MEDICAL.
        '''</summary>
        Friend Shared ReadOnly Property ingreMed() As String
            Get
                Return ResourceManager.GetString("ingreMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Thursday.
        '''</summary>
        Friend Shared ReadOnly Property Jue() As String
            Get
                Return ResourceManager.GetString("Jue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update Personal Data.
        '''</summary>
        Friend Shared ReadOnly Property lbActuDatos() As String
            Get
                Return ResourceManager.GetString("lbActuDatos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Change Password.
        '''</summary>
        Friend Shared ReadOnly Property lbCambiarContraseña() As String
            Get
                Return ResourceManager.GetString("lbCambiarContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Update.
        '''</summary>
        Friend Shared ReadOnly Property lbCambiarFoto() As String
            Get
                Return ResourceManager.GetString("lbCambiarFoto", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a PASSWORD.
        '''</summary>
        Friend Shared ReadOnly Property lbContraseña() As String
            Get
                Return ResourceManager.GetString("lbContraseña", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Description.
        '''</summary>
        Friend Shared ReadOnly Property lbDescripcion() As String
            Get
                Return ResourceManager.GetString("lbDescripcion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a REMOVE.
        '''</summary>
        Friend Shared ReadOnly Property lbEliminar() As String
            Get
                Return ResourceManager.GetString("lbEliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Software created by VVB Software.
        '''</summary>
        Friend Shared ReadOnly Property lbHechoPor() As String
            Get
                Return ResourceManager.GetString("lbHechoPor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Icons Made By:.
        '''</summary>
        Friend Shared ReadOnly Property lbIconoHechos() As String
            Get
                Return ResourceManager.GetString("lbIconoHechos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a In case you have not changed your password, this will be your ID.
        '''If I modify it, you can click on the following link to restore it.
        '''</summary>
        Friend Shared ReadOnly Property lbInfo_recordatorio2() As String
            Get
                Return ResourceManager.GetString("lbInfo_recordatorio2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a In case you do not have an account, click here.
        '''</summary>
        Friend Shared ReadOnly Property lbInfo_recordatorio3() As String
            Get
                Return ResourceManager.GetString("lbInfo_recordatorio3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Remember that the ID must NOT contain periods or hyphens.
        '''</summary>
        Friend Shared ReadOnly Property lbInfo_rocordatorio1() As String
            Get
                Return ResourceManager.GetString("lbInfo_rocordatorio1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a http://www.freepik.com.
        '''</summary>
        Friend Shared ReadOnly Property lbLinkIconos() As String
            Get
                Return ResourceManager.GetString("lbLinkIconos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property lbNomEnf() As String
            Get
                Return ResourceManager.GetString("lbNomEnf", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Name.
        '''</summary>
        Friend Shared ReadOnly Property lbNomSint() As String
            Get
                Return ResourceManager.GetString("lbNomSint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Risk.
        '''</summary>
        Friend Shared ReadOnly Property lbRiesgo() As String
            Get
                Return ResourceManager.GetString("lbRiesgo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Click the image.
        '''</summary>
        Friend Shared ReadOnly Property lbSelecImagen() As String
            Get
                Return ResourceManager.GetString("lbSelecImagen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USER.
        '''</summary>
        Friend Shared ReadOnly Property lbUsuario() As String
            Get
                Return ResourceManager.GetString("lbUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREATE USER.
        '''</summary>
        Friend Shared ReadOnly Property llbCrearUsuario() As String
            Get
                Return ResourceManager.GetString("llbCrearUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FORGOT YOUR PASSWORD ?.
        '''</summary>
        Friend Shared ReadOnly Property llbForgotPassEs() As String
            Get
                Return ResourceManager.GetString("llbForgotPassEs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Monday.
        '''</summary>
        Friend Shared ReadOnly Property Lun() As String
            Get
                Return ResourceManager.GetString("Lun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Tuesday.
        '''</summary>
        Friend Shared ReadOnly Property Mar() As String
            Get
                Return ResourceManager.GetString("Mar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnosis.
        '''</summary>
        Friend Shared ReadOnly Property MChat_diag() As String
            Get
                Return ResourceManager.GetString("MChat_diag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Time.
        '''</summary>
        Friend Shared ReadOnly Property Mhora() As String
            Get
                Return ResourceManager.GetString("Mhora", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Departure time.
        '''</summary>
        Friend Shared ReadOnly Property MhoraSalida() As String
            Get
                Return ResourceManager.GetString("MhoraSalida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Wednesday.
        '''</summary>
        Friend Shared ReadOnly Property Mie() As String
            Get
                Return ResourceManager.GetString("Mie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Double click on a cell to select the item.
        '''</summary>
        Friend Shared ReadOnly Property modifAclaracion() As String
            Get
                Return ResourceManager.GetString("modifAclaracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFY.
        '''</summary>
        Friend Shared ReadOnly Property modificar() As String
            Get
                Return ResourceManager.GetString("modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Double click to start chat.
        '''</summary>
        Friend Shared ReadOnly Property MSoli_aclaracion() As String
            Get
                Return ResourceManager.GetString("MSoli_aclaracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CHAT REQUESTS.
        '''</summary>
        Friend Shared ReadOnly Property MSoli_titulo() As String
            Get
                Return ResourceManager.GetString("MSoli_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECT YOUR SYMPTOMS.
        '''</summary>
        Friend Shared ReadOnly Property PConsulta_titulo() As String
            Get
                Return ResourceManager.GetString("PConsulta_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a (no dots or dashes).
        '''</summary>
        Friend Shared ReadOnly Property Persona_aclaracionCi() As String
            Get
                Return ResourceManager.GetString("Persona_aclaracionCi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Family background.
        '''</summary>
        Friend Shared ReadOnly Property Persona_antece() As String
            Get
                Return ResourceManager.GetString("Persona_antece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Writ identity.
        '''</summary>
        Friend Shared ReadOnly Property Persona_ci() As String
            Get
                Return ResourceManager.GetString("Persona_ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Email.
        '''</summary>
        Friend Shared ReadOnly Property Persona_correo() As String
            Get
                Return ResourceManager.GetString("Persona_correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Address.
        '''</summary>
        Friend Shared ReadOnly Property Persona_dir() As String
            Get
                Return ResourceManager.GetString("Persona_dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Home.
        '''</summary>
        Friend Shared ReadOnly Property Persona_domicilio() As String
            Get
                Return ResourceManager.GetString("Persona_domicilio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Age.
        '''</summary>
        Friend Shared ReadOnly Property Persona_edad() As String
            Get
                Return ResourceManager.GetString("Persona_edad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Specialty.
        '''</summary>
        Friend Shared ReadOnly Property Persona_especialidad() As String
            Get
                Return ResourceManager.GetString("Persona_especialidad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Workplace.
        '''</summary>
        Friend Shared ReadOnly Property Persona_lugarTrabajo() As String
            Get
                Return ResourceManager.GetString("Persona_lugarTrabajo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Doctor number.
        '''</summary>
        Friend Shared ReadOnly Property Persona_numMed() As String
            Get
                Return ResourceManager.GetString("Persona_numMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Surname.
        '''</summary>
        Friend Shared ReadOnly Property Persona_pApe() As String
            Get
                Return ResourceManager.GetString("Persona_pApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Password.
        '''</summary>
        Friend Shared ReadOnly Property Persona_pass() As String
            Get
                Return ResourceManager.GetString("Persona_pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a First name.
        '''</summary>
        Friend Shared ReadOnly Property Persona_pNom() As String
            Get
                Return ResourceManager.GetString("Persona_pNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Second surname.
        '''</summary>
        Friend Shared ReadOnly Property Persona_sApe() As String
            Get
                Return ResourceManager.GetString("Persona_sApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sex.
        '''</summary>
        Friend Shared ReadOnly Property Persona_sexo() As String
            Get
                Return ResourceManager.GetString("Persona_sexo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Second name.
        '''</summary>
        Friend Shared ReadOnly Property Persona_sNom() As String
            Get
                Return ResourceManager.GetString("Persona_sNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Phone.
        '''</summary>
        Friend Shared ReadOnly Property Persona_tel() As String
            Get
                Return ResourceManager.GetString("Persona_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Background.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_antecedentes() As String
            Get
                Return ResourceManager.GetString("PFicha_antecedentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Which one.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_cual() As String
            Get
                Return ResourceManager.GetString("PFicha_cual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Reason for consultation*.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_motCons() As String
            Get
                Return ResourceManager.GetString("PFicha_motCons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Occupation *.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_ocup() As String
            Get
                Return ResourceManager.GetString("PFicha_ocup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Origin*.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_proced() As String
            Get
                Return ResourceManager.GetString("PFicha_proced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICAL RECORD.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_titulo() As String
            Get
                Return ResourceManager.GetString("PFicha_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Take medicine?.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_tomaMed() As String
            Get
                Return ResourceManager.GetString("PFicha_tomaMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a new password.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_passNueva() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_passNueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repeat password.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_passNueva2() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_passNueva2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECOVER PASSWORD.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_titulo() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Your username is:.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_usuario() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Saturday.
        '''</summary>
        Friend Shared ReadOnly Property Sab() As String
            Get
                Return ResourceManager.GetString("Sab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Select a filter.
        '''</summary>
        Friend Shared ReadOnly Property selecFiltro() As String
            Get
                Return ResourceManager.GetString("selecFiltro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Symptom.
        '''</summary>
        Friend Shared ReadOnly Property sintoma() As String
            Get
                Return ResourceManager.GetString("sintoma", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICAL SELF-CONSULTATION SYSTEM.
        '''</summary>
        Friend Shared ReadOnly Property titulo_app() As String
            Get
                Return ResourceManager.GetString("titulo-app", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Friday.
        '''</summary>
        Friend Shared ReadOnly Property Vie() As String
            Get
                Return ResourceManager.GetString("Vie", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
