'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'StronglyTypedResourceBuilder generó automáticamente esta clase
    'a través de una herramienta como ResGen o Visual Studio.
    'Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    'con la opción /str o recompile su proyecto de VS.
    '''<summary>
    '''  Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Res
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Presentation.Res", GetType(Res).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        '''  búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BIENVENIDO.
        '''</summary>
        Friend Shared ReadOnly Property Bienvenida_bienvenida() As String
            Get
                Return ResourceManager.GetString("Bienvenida_bienvenida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SISTEMA DE AUTOCONSULTA MEDICA.
        '''</summary>
        Friend Shared ReadOnly Property Bienvenida_titulo() As String
            Get
                Return ResourceManager.GetString("Bienvenida_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a BIENVENIDO.
        '''</summary>
        Friend Shared ReadOnly Property Bienvenido() As String
            Get
                Return ResourceManager.GetString("Bienvenido", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ACEPTAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_aceptar() As String
            Get
                Return ResourceManager.GetString("btn_aceptar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a AGENDA MEDICA.
        '''</summary>
        Friend Shared ReadOnly Property btn_Agenda() As String
            Get
                Return ResourceManager.GetString("btn_Agenda", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CANCELAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_cancelar() As String
            Get
                Return ResourceManager.GetString("btn_cancelar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CERRAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_cerrar() As String
            Get
                Return ResourceManager.GetString("btn_cerrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CERRAR SESION.
        '''</summary>
        Friend Shared ReadOnly Property btn_cerrarSesion() As String
            Get
                Return ResourceManager.GetString("btn_cerrarSesion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CHAT.
        '''</summary>
        Friend Shared ReadOnly Property btn_chat() As String
            Get
                Return ResourceManager.GetString("btn_chat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CHATS.
        '''</summary>
        Friend Shared ReadOnly Property btn_chats() As String
            Get
                Return ResourceManager.GetString("btn_chats", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONSULTAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_consultar() As String
            Get
                Return ResourceManager.GetString("btn_consultar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_crear() As String
            Get
                Return ResourceManager.GetString("btn_crear", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ELIMINAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_eliminar() As String
            Get
                Return ResourceManager.GetString("btn_eliminar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ENTRE.
        '''</summary>
        Friend Shared ReadOnly Property btn_Entre() As String
            Get
                Return ResourceManager.GetString("btn_Entre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ENVIAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_enviar() As String
            Get
                Return ResourceManager.GetString("btn_enviar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FICHA MEDICA.
        '''</summary>
        Friend Shared ReadOnly Property btn_fichaMed() As String
            Get
                Return ResourceManager.GetString("btn_fichaMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FILTRAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_Filtrar() As String
            Get
                Return ResourceManager.GetString("btn_Filtrar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a HISTORIAL.
        '''</summary>
        Friend Shared ReadOnly Property btn_historial() As String
            Get
                Return ResourceManager.GetString("btn_historial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INGRESAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_ingresar() As String
            Get
                Return ResourceManager.GetString("btn_ingresar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MEDICOS.
        '''</summary>
        Friend Shared ReadOnly Property btn_ingrMed() As String
            Get
                Return ResourceManager.GetString("btn_ingrMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a INICIAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_Iniciar() As String
            Get
                Return ResourceManager.GetString("btn_Iniciar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a MODIFICAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_modificar() As String
            Get
                Return ResourceManager.GetString("btn_modificar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECUPERAR.
        '''</summary>
        Friend Shared ReadOnly Property btn_recuperar() As String
            Get
                Return ResourceManager.GetString("btn_recuperar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RESTABLECER.
        '''</summary>
        Friend Shared ReadOnly Property btn_restablecer() As String
            Get
                Return ResourceManager.GetString("btn_restablecer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SALIR.
        '''</summary>
        Friend Shared ReadOnly Property btn_salir() As String
            Get
                Return ResourceManager.GetString("btn_salir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SOLICITUDES DE CHAT.
        '''</summary>
        Friend Shared ReadOnly Property btn_soliChat() As String
            Get
                Return ResourceManager.GetString("btn_soliChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CONTRASEÑA.
        '''</summary>
        Friend Shared ReadOnly Property contra() As String
            Get
                Return ResourceManager.GetString("contra", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a CREAR USUARIO.
        '''</summary>
        Friend Shared ReadOnly Property crearUsuario() As String
            Get
                Return ResourceManager.GetString("crearUsuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Domingo.
        '''</summary>
        Friend Shared ReadOnly Property Dom() As String
            Get
                Return ResourceManager.GetString("Dom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Por favor espere.
        '''</summary>
        Friend Shared ReadOnly Property EsperaChat() As String
            Get
                Return ResourceManager.GetString("EsperaChat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Filtro.
        '''</summary>
        Friend Shared ReadOnly Property filtro() As String
            Get
                Return ResourceManager.GetString("filtro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En caso de no haber cambiado su contraseña, esta sera su cedula. 
        '''Si la modifico puede dar click en el siguiente enlace para restablecerla.
        '''</summary>
        Friend Shared ReadOnly Property Info_recordatorio2() As String
            Get
                Return ResourceManager.GetString("Info_recordatorio2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a En caso de no tener una cuenta de click aquí.
        '''</summary>
        Friend Shared ReadOnly Property Info_recordatorio3() As String
            Get
                Return ResourceManager.GetString("Info_recordatorio3", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Recuerde que la cedula NO debe contener puntos ni guiones.
        '''</summary>
        Friend Shared ReadOnly Property Info_rocordatorio() As String
            Get
                Return ResourceManager.GetString("Info_rocordatorio", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Jueves.
        '''</summary>
        Friend Shared ReadOnly Property Jue() As String
            Get
                Return ResourceManager.GetString("Jue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a OLVIDO SU CONTRASEÑA ?.
        '''</summary>
        Friend Shared ReadOnly Property llbForgotPassEs() As String
            Get
                Return ResourceManager.GetString("llbForgotPassEs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Lunes.
        '''</summary>
        Friend Shared ReadOnly Property Lun() As String
            Get
                Return ResourceManager.GetString("Lun", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Martes.
        '''</summary>
        Friend Shared ReadOnly Property Mar() As String
            Get
                Return ResourceManager.GetString("Mar", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Diagnostico.
        '''</summary>
        Friend Shared ReadOnly Property MChat_diag() As String
            Get
                Return ResourceManager.GetString("MChat_diag", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hora de entrada.
        '''</summary>
        Friend Shared ReadOnly Property MhoraEntrada() As String
            Get
                Return ResourceManager.GetString("MhoraEntrada", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Hora de salida.
        '''</summary>
        Friend Shared ReadOnly Property MhoraSalida() As String
            Get
                Return ResourceManager.GetString("MhoraSalida", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Miercoles.
        '''</summary>
        Friend Shared ReadOnly Property Mie() As String
            Get
                Return ResourceManager.GetString("Mie", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a De doble click para iniciar chat.
        '''</summary>
        Friend Shared ReadOnly Property MSoli_aclaracion() As String
            Get
                Return ResourceManager.GetString("MSoli_aclaracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SOLICITUDES DE CHAT.
        '''</summary>
        Friend Shared ReadOnly Property MSoli_titulo() As String
            Get
                Return ResourceManager.GetString("MSoli_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SELECCIONE SUS SINTOMAS.
        '''</summary>
        Friend Shared ReadOnly Property PConsulta_titulo() As String
            Get
                Return ResourceManager.GetString("PConsulta_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antecedentes Familiares.
        '''</summary>
        Friend Shared ReadOnly Property Persona_antece() As String
            Get
                Return ResourceManager.GetString("Persona_antece", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cedula Identidad.
        '''</summary>
        Friend Shared ReadOnly Property Persona_ci() As String
            Get
                Return ResourceManager.GetString("Persona_ci", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Correo Electronico.
        '''</summary>
        Friend Shared ReadOnly Property Persona_correo() As String
            Get
                Return ResourceManager.GetString("Persona_correo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Direccion.
        '''</summary>
        Friend Shared ReadOnly Property Persona_dir() As String
            Get
                Return ResourceManager.GetString("Persona_dir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Edad.
        '''</summary>
        Friend Shared ReadOnly Property Persona_edad() As String
            Get
                Return ResourceManager.GetString("Persona_edad", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primer Nombre.
        '''</summary>
        Friend Shared ReadOnly Property Persona_pApe() As String
            Get
                Return ResourceManager.GetString("Persona_pApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña.
        '''</summary>
        Friend Shared ReadOnly Property Persona_pass() As String
            Get
                Return ResourceManager.GetString("Persona_pass", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Primer Apellido.
        '''</summary>
        Friend Shared ReadOnly Property Persona_pNom() As String
            Get
                Return ResourceManager.GetString("Persona_pNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Segundo Apellido.
        '''</summary>
        Friend Shared ReadOnly Property Persona_sApe() As String
            Get
                Return ResourceManager.GetString("Persona_sApe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Segundo Nombre.
        '''</summary>
        Friend Shared ReadOnly Property Persona_sNom() As String
            Get
                Return ResourceManager.GetString("Persona_sNom", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Telefono.
        '''</summary>
        Friend Shared ReadOnly Property Persona_tel() As String
            Get
                Return ResourceManager.GetString("Persona_tel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Antecedentes.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_antecedentes() As String
            Get
                Return ResourceManager.GetString("PFicha_antecedentes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Cual.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_cual() As String
            Get
                Return ResourceManager.GetString("PFicha_cual", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Motivo de la consulta.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_motCons() As String
            Get
                Return ResourceManager.GetString("PFicha_motCons", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Ocupacion.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_ocup() As String
            Get
                Return ResourceManager.GetString("PFicha_ocup", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Procedencia.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_proced() As String
            Get
                Return ResourceManager.GetString("PFicha_proced", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a FICHA MEDICA.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_titulo() As String
            Get
                Return ResourceManager.GetString("PFicha_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a ¿Toma medicina?.
        '''</summary>
        Friend Shared ReadOnly Property PFicha_tomaMed() As String
            Get
                Return ResourceManager.GetString("PFicha_tomaMed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Esta fecha debe ser mayor.
        '''</summary>
        Friend Shared ReadOnly Property Phistorial_Aclaracion() As String
            Get
                Return ResourceManager.GetString("Phistorial Aclaracion", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Contraseña nueva.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_passNueva() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_passNueva", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Repita la contraseña.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_passNueva2() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_passNueva2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a RECUPERAR CONTRASEÑA.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_titulo() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_titulo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Su usuario es:.
        '''</summary>
        Friend Shared ReadOnly Property RecuperarPass_usuario() As String
            Get
                Return ResourceManager.GetString("RecuperarPass_usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Sabado.
        '''</summary>
        Friend Shared ReadOnly Property Sab() As String
            Get
                Return ResourceManager.GetString("Sab", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a SISTEMA DE AUTOCONSULTA MEDICA.
        '''</summary>
        Friend Shared ReadOnly Property titulo_app() As String
            Get
                Return ResourceManager.GetString("titulo-app", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a USUARIO.
        '''</summary>
        Friend Shared ReadOnly Property usuario() As String
            Get
                Return ResourceManager.GetString("usuario", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Busca una cadena traducida similar a Viernes.
        '''</summary>
        Friend Shared ReadOnly Property Vie() As String
            Get
                Return ResourceManager.GetString("Vie", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
